const RB_DATA = {
  id: 1,
  title: 'RayBan',
  routeName: 'rayban',
  type: 'sunglasses',
  polarized: [],
  items: [
    {
      id: 1,
      model: 'RB3025',
      shape: 'pilot',
      material: 'metal',
      type: 'full-rim',
      color: [
        {
          frame_color: 'gold',
          lens: [
            {
              lens_color: 'Crystal_Brown',
              color_code: '001/57',
              model_code: 'RB3025',
              polarized: true,
              size: [58],
              price: 263,
              imgUrl: '/images/shop-img/rayban/RB302500157.png',
              linkUrl: '/RB302500157',
            },
            {
              lens_color: 'Crystal_Green',
              color_code: '001/58',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58, 62],
              price: 263,
              imgUrl: '/images/shop-img/rayban/RB302500158.png',
              linkUrl: '/RB302500158',
            },
            {
              lens_color: 'Gradient_Blue',
              color_code: '001/78',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58, 62],
              price: 263,
              imgUrl: '/images/shop-img/rayban/RB302500178.png',
              linkUrl: '/RB302500178',
            },
          ],
        },
        {
          frame_color: 'gunmetal',
          lens: [
            {
              lens_color: 'Crystal_Polar_Blue_Gradient_Grey',
              color_code: '004/78',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58],
              price: 263,
              imgUrl: '/images/shop-img/rayban/RB302500478.png',
              linkUrl: '/RB302500478',
            },
            {
              lens_color: 'Crystal_Green',
              color_code: '001/58',
              model_code: 'RB3025',
              polarized: true,
              size: [58, 62],
              price: 263,
              imgUrl: '/images/shop-img/rayban/RB302500458.png',
              linkUrl: '/RB302500458',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      model: 'RB1972',
      shape: 'octagon',
      material: 'metal',
      type: 'full-rim',
      color: [
        {
          frame_color: 'silver',
          lens: [
            {
              lens_color: 'Blue_Gradient',
              color_code: '914978',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/rayban/RB1972914978.png',
              linkUrl: '/RB1972914978',
            },
            {
              lens_color: 'Green',
              color_code: '914931',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/rayban/RB1972914931.png',
              linkUrl: '/RB1972914931',
            },
            {
              lens_color: 'Clear_Gradient_Blue',
              color_code: '91493F',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/rayban/RB197291493F.png',
              linkUrl: '/RB197291493F',
            },
          ],
        },

        {
          frame_color: 'gold',
          lens: [
            {
              lens_color: 'Clear_Gradient_Brown',
              color_code: '914751',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/rayban/RB1972914751.png',
              linkUrl: '/RB1972914751',
            },
            {
              lens_color: 'Dark_Grey',
              color_code: '9150B1',
              model_code: 'RB1972',
              polarized: true,
              size: [58, 62],
              price: 100,
              imgUrl: '/images/shop-img/rayban/RB19729150B1.png',
              linkUrl: '/RB19729150B1',
            },
          ],
        },
      ],
    },
  ],
};

export default RB_DATA;
