const SUNGLASSES_DATA = {
  id: 1,
  title: 'Sunglasses',
  //   routeName: 'rayban',
  //   type: 'sunglasses',
  items: [
    {
      id: 1,
      brand: 'RayBan',
      gender: 'men',
      productType: 'sunglasses',
      model: 'RB3025',
      shape: 'Pilot',
      material: 'Metal',
      frameType: 'Full-Frame',
      color: [
        {
          frame_color: 'Gold',
          lens: [
            {
              lens_color: 'Crystal Brown',
              color_code: '001/57',
              model_code: 'RB3025',
              polarized: true,
              size: [58],
              price: 263,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB302500157.png',
              linkUrl: '/RB302500157',
            },
            {
              lens_color: 'Crystal Green',
              color_code: '001/58',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58, 62],
              price: 263,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB302500158.png',
              linkUrl: '/RB302500158',
            },
            {
              lens_color: 'Gradient Blue',
              color_code: '001/78',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58, 62],
              price: 263,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB302500178.png',
              linkUrl: '/RB302500178',
            },
          ],
        },
        {
          frame_color: 'Gunmetal',
          lens: [
            {
              lens_color: 'Crystal Polar Blue Gradient Grey',
              color_code: '004/78',
              model_code: 'RB3025',
              polarized: true,
              size: [55, 58],
              price: 263,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB302500478.png',
              linkUrl: '/RB302500478',
            },
            {
              lens_color: 'Crystal Green',
              color_code: '001/58',
              model_code: 'RB3025',
              polarized: true,
              size: [58, 62],
              price: 263,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB302500458.png',
              linkUrl: '/RB302500458',
            },
          ],
        },
      ],
    },
    {
      id: 2,
      brand: 'RayBan',
      model: 'RB1972',
      gender: 'both',
      productType: 'sunglasses',
      shape: 'Octagon',
      material: 'Metal',
      frameType: 'Full-Frame',
      color: [
        {
          frame_color: 'Silver',
          lens: [
            {
              lens_color: 'Blue Gradient',
              color_code: '914978',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB1972914978.png',
              linkUrl: '/RB1972914978',
            },
            {
              lens_color: 'Green',
              color_code: '914931',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB1972914931.png',
              linkUrl: '/RB1972914931',
            },
            {
              lens_color: 'Clear Gradient Blue',
              color_code: '91493F',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB197291493F.png',
              linkUrl: '/RB197291493F',
            },
          ],
        },

        {
          frame_color: 'Gold',
          lens: [
            {
              lens_color: 'Clear Gradient Brown',
              color_code: '914751',
              model_code: 'RB1972',
              polarized: true,
              size: [54],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB1972914751.png',
              linkUrl: '/RB1972914751',
            },
            {
              lens_color: 'Dark Grey',
              color_code: '9150B1',
              model_code: 'RB1972',
              polarized: true,
              size: [58, 62],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/rayban/RB19729150B1.png',
              linkUrl: '/RB19729150B1',
            },
          ],
        },
      ],
    },
    {
      id: 3,
      brand: 'Burberry',
      gender: 'women',
      model: 'BE4307',
      productType: 'sunglasses',
      shape: 'Octagon',
      material: 'Plastic',
      frameType: 'Full-Frame',
      color: [
        {
          frame_color: 'Havana Brown',
          lens: [
            {
              lens_color: 'Brown',
              color_code: '366073',
              model_code: 'BE4307',
              polarized: false,
              size: [50],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/burberry/BE4307366073.png',
              linkUrl: '/BE4307366073',
            },
          ],
        },

        {
          frame_color: 'Transparent Grey',
          lens: [
            {
              lens_color: 'Gray Gradient Blue',
              color_code: '38314L',
              model_code: 'BE4307',
              polarized: false,
              size: [50],
              price: 100,
              imgUrl: '/images/shop-img/sunglasses/burberry/BE430738314L.png',
              linkUrl: '/BE430738314L',
            },
          ],
        },
      ],
    },
  ],
};

export default SUNGLASSES_DATA;
